UNPM_PKG_NAME = "todo"
UNPM_PKG_DESCRIPTION = "Simple todo cli"
UNPM_PKG_LICENSE = "MIT License"
UNPM_PKG_MAINTAINER = "@nazhard"
UNPM_PKG_HOMEPAGE = ""
UNPM_PKG_VERSION = "0.1.0"
UNPM_PKG_SRCURL = "https://raw.githubusercontent.com/nazhard/random/main/packages/todo/todo"
UNPM_PKG_BUILD_SCRIPT = ""
UNPM_PKG_DEPENS = ""
