UNPM_PKG_NAME = "todo"
UNPM_PKG_DESCRIPTION = "Simple todo cli"
UNPM_PKG_LICENSE = "MIT License"
UNPM_PKG_MAINTAINER = "@nazhard"
UNPM_PKG_HOMEPAGE = ""
UNPM_PKG_VERSION = "0.0.1"
UNPM_PKG_SRCURL = "https://github.com/nazhard/todo-cli/releases/download/v0.0.1/todo"
UNPM_PKG_BUILD_SCRIPT = ""
UNPM_PKG_DEPENS = ""
